#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from textwrap import indent


DEFAULT_OUTPUT = Path("packages/xlm-ns-sdk-py/src/xlm_ns_sdk/generated.py")


def load_manifest(spec_dir: Path) -> dict:
    manifest = spec_dir / "contracts.json"
    if manifest.exists():
        return json.loads(manifest.read_text(encoding="utf-8"))
    raise SystemExit(f"missing manifest: {manifest}")


def build_source(manifest: dict) -> str:
    lines = [
        "from __future__ import annotations",
        "",
        "# Auto-generated by scripts/generate_python_sdk.py.",
        "",
        "from dataclasses import asdict",
        "from typing import Any, Dict, List, Optional",
        "",
        "from .backend import AsyncContractBackend, ContractInvocation",
        "from .models import *",
        "",
        "class _ContractClientBase:",
        "    def __init__(self, backend: AsyncContractBackend, contract_name: str, contract_id: Optional[str]) -> None:",
        "        self._backend = backend",
        "        self._contract_name = contract_name",
        "        self._contract_id = contract_id",
        "",
        "    async def _read(self, method: str, **arguments: Any) -> Any:",
        "        return await self._backend.call(ContractInvocation(self._contract_name, self._contract_id, method, arguments, mode=\"read\"))",
        "",
        "    async def _write(self, method: str, **arguments: Any) -> Any:",
        "        return await self._backend.call(ContractInvocation(self._contract_name, self._contract_id, method, arguments, mode=\"write\"))",
        "",
    ]
    for contract in manifest["contracts"]:
        class_name = contract["class_name"]
        lines.append(f"class {class_name}(_ContractClientBase):")
        for method in contract["methods"]:
            lines.append(f"    async def {method['name']}(self, **kwargs: Any) -> Any:")
            lines.append(
                f"        return await self._{'write' if method.get('mode') == 'write' else 'read'}('{method['name']}', **kwargs)"
            )
            lines.append("")
        if lines[-1] == "":
            lines.pop()
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the Python SDK bindings from a contract manifest.")
    parser.add_argument("--spec-dir", type=Path, default=Path("packages/xlm-ns-sdk-py/specs"))
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    manifest = load_manifest(args.spec_dir)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(build_source(manifest), encoding="utf-8")


if __name__ == "__main__":
    main()

